name: CI/CD Node.js - Générateur de citations

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    name: Continuous Deployment
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate dynamic index.html
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='fr'>" >> index.html
          echo "<head><meta charset='UTF-8'><title>TP Node.js CI/CD</title></head>" >> index.html
          echo "<body>" >> index.html
          echo "<h1>Devoir Node.js CI/CD</h1>" >> index.html
          echo "<p> Le succès est la somme de petits efforts répétés jour après jour</p>" >> index.html
          echo "</body></html>" >> index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
